[project]
name = 'Dyson-Sphere-Construction-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.construction-coordination]
path = 'contracts/construction-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-capture-module]
path = 'contracts/energy-capture-module.clar'
clarity_version = 2
epoch = 2.5

[contracts.maintenance-drone-fleet]
path = 'contracts/maintenance-drone-fleet.clar'
clarity_version = 2
epoch = 2.5

[contracts.power-distribution]
path = 'contracts/power-distribution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
